# Generated by Django 4.2.4 on 2024-02-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontnd', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
